### ISSUE TITLE
ESM version

### ISSUE THREAD

**Issue by gugu** [runk/mmdb-lib#11]
Currently, this module (js version) has this piece of code:

`exports.default = Reader;`

This code if it is used in ESM module is exported as named export `default`, which is hard to import and it is inconsistent with types.

For example:

```javascript
import Reader from 'mmdb-lib'; // Reader is equal to {default: ActuallyReader}
import {default as Reader} from 'mmdb-lib'; // Reader is equal to {default: ActuallyReader} because default is a special keyword here
```

The only way to import Reader correctly from typescript + native ESM without esModuleInterop is: 

```javascript
import * as MMDB from 'mmdb-lib';
const Reader = (MMDB.default as unknown as typeof MMDB).default;
```

**Comment by runk** [comment]
Apologies for the delay, just looked into it. The most straightfoward way I was able to find for address it is to make `Reader` a named export.

Out in https://github.com/runk/mmdb-lib/releases/tag/v2.0.0
