### ISSUE TITLE
Issue with node version check

### ISSUE THREAD

**Issue by michael-meetkai** [runk/mmdb-lib#192]
Hey!
I'm getting this error using `@maxmind/geoip2-node` while creating a new instance of `WebServiceClient`. I tried with node 18 and 20

Probably related to https://github.com/runk/mmdb-lib/blob/76da6db91b8fa9080c7390cf6dd52f99e873a505/src/decoder.ts#L5

![Screenshot 2024-05-28 214951](https://github.com/runk/mmdb-lib/assets/143638292/726ffb69-28ec-44ec-b5cd-3508d0a6405b)

Any ideas?

**Comment by runk** [comment]
I believe it should be fixed with #193. Please try mmdb-lib@2.1.1
