### ISSUE TITLE
Feature Request: Consider integrating WASM option

### ISSUE THREAD

**Issue by josh-hemphill** [runk/mmdb-lib#4]
I'm not sure how the performance would compare, but I have a project you could use as an example [masxminddb-deno](https://github.com/josh-hemphill/maxminddb-deno), where I used the maxminddb Rust library to build a webassembly module and a wrapper around it in Deno.

Another possible benefit aside from any potential performance is that it would give a way to to consume `Uint8Array`s

**Comment by runk** [comment]
Yeah I was thinking about that some time ago too. Worth giving it a benchmark and comparing numbers I think. Last time I checked it, unmarshalling responses from WASM module wasn't as fast as I hoped, which had eaten all performance improvements WASM brings..

**Comment by runk** [comment]
Really long overdue update: after experiments I concluded it does not worth it - performance of (de)serialising data between two worlds is killing the performance. It would make sense for the case where a lot more complex computation happen in javascript.
