### ISSUE TITLE
Request for supporting older version of node

### ISSUE THREAD

**Issue by PratikYagnik** [runk/mmdb-lib#6]
Hey, I have a project which runs on the older version of the node (8.4.0).  after including this library it fails due to node version required is 10.4 or above.

After digging a little more I got to know that it requires BigInt.

> assert_1.default(typeof BigInt !== 'undefined', 'Apparently you are using old version of node. Please upgrade to node 10.4.x or above.');

Is it possible to add **https://www.npmjs.com/package/big-integer** as a dependency that polyfills BigInt?

**Comment by runk** [comment]
Not sure I want to do that, sorry. Node 10 is like 3 year old now, or 2 LTS releases behind.

As a workaround I recommend you looking for an older release (from 2018-2019) of `maxmind` npm module, like this one https://github.com/runk/node-maxmind/tree/v3.0.0

Good luck
